name : Portfolio Deployment

on:
  Push:
    branches:
    - main

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
    uses: aws-actions/configure-awscredentials@v1
    with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
    aws-secret-access-key :${{secrets.AWS_SECRET_ACCESS_KEY}}
    aws-regin: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://myportfoli --delete
    
      
